# SPDX-FileCopyrightText: © 2024 Matthew Rothlisberger
# SPDX-License-Identifier: CC-BY-SA-4.0

# Rights to the bGain trademark are reserved; see the COPYRIGHT file.

* bGain

=bgain [-h] [-o] [-c <path to config>]=

Retrieves your latest blood glucose and the change since your last
reading from your Nightscout server. Publishes a string containing
both, along with a trend arrow, to a temporary file in your
filesystem. Repeats after an interval approximately matching the
interval at which your server gets readings.

This program is intended to facilitate placing a blood glucose
indicator on your desktop, a status bar, or in your own programs. Your
script can simply read from the temporary file. bGain will make sure
that the file is up-to-date.

Here's an example shell script to update your X root window title with
your current blood glucose:

#+begin_src bash
#!/usr/bin/bash

gluc=$(cat /tmp/bgain-latest)
xsetroot -name "$gluc"
#+end_src

By default, bGain reads configuration from
=$HOME/.config/bgain/bgain.cfg=; see the example config in the
=bgain.def.cfg= file. Copy this to the mentioned path and substitute
in the URL and token for your server.

A systemd unit file is also provided. After installing it, run
=systemctl --user enable --now bgain= to start bGain, which will run
indefinitely, updating its temporary file promptly with each new
reading.

This program uses Linux x86-64 system calls directly and will not work
without modification on other operating systems or
architectures. Known compatible with the API of Nightscout
cgm-remote-monitor versions 14 and higher.

